### ISSUE TITLE
Display Limit

### ISSUE THREAD

**Issue by gofisk** [KillerCodeMonkey/ionic-starter-maps#6]
I see in the demo data.js there are 30 events or so, yet it only shows 5 when you launch the app. How can you change this so it will show all of the events?

**Comment by KillerCodeMonkey** [comment]
This is only an example like a preview of the latest 5 events for the startpage. If you want to get more you can change the limit or remove it. It is only an example --> e.g. you could add a Button to show all events in the event list.

**Comment by gofisk** [comment]
Ok, where exactly would you change this limit? I tried a few things, but can't seem to get it to work.

**Comment by KillerCodeMonkey** [comment]
there is a special function in the eventServe called getNext()
https://github.com/KillerCodeMonkey/ionic-starter-eventmaps/blob/master/www/app/services/event.js

there the result is limited to 5 --> it is something like simulating an API-endpoint which returns the next 5 events
