### ISSUE TITLE
Doesnt work with cordova platform add ....

### ISSUE THREAD

**Issue by stevmachine** [KillerCodeMonkey/ionic-starter-maps#8]
Hi, i try to make a 'cordova platform add android' and ' cordova platform run android' but fails, what i need to make works?

**Comment by KillerCodeMonkey** [comment]
first you should use `ionic platform add xxx` and `ionic platform run xxx` to use ionic build process.

Could you share your error message?

**Comment by KillerCodeMonkey** [comment]
Any updates? In other cases i will close the issue soon

**Comment by stevmachine** [comment]
yeah, i try that, the error i got is i dont have the icons :(

**Comment by KillerCodeMonkey** [comment]
take a look where the ionic sources are. in the ionic.app.scss in /scss it is referencing this:

``` scss
// The path for our ionicons font files, relative to the built CSS in www/css
$ionicons-font-path: "../lib/ionic/fonts" !default;

// Include all of Ionic
@import "www/lib/ionic/scss/ionic";
```

**Comment by stevmachine** [comment]
i try the ionics commands, i got this now:

![image](https://cloud.githubusercontent.com/assets/17983441/15248186/34d17594-18ef-11e6-9c49-827f2f5a89ff.png)

**Comment by KillerCodeMonkey** [comment]
you do not need the "platform" command 

`ionic run android` is enough

**Comment by stevmachine** [comment]
oh thats work, now make the apk.! 

Doesnt have plugins?, i got this error from chrome inspector.

![image](https://cloud.githubusercontent.com/assets/17983441/15248365/353bafa8-18f0-11e6-8721-ba4d33749446.png)

How i can install the plugins and install the require?, sorry for nooby questions.

**Comment by stevmachine** [comment]
ionic state restore --plugins (for install plugins) 

Is missing the dependency of require in package.json.

**Comment by KillerCodeMonkey** [comment]
Nope requirejs is in the lib folder, but maybe you updated ionic so the lib folder was cleared.

Look in the sources here on github:
/www/lib/requirejs

If you want --> add requirejs to the bower.json then it will be automatically installed.

**Comment by stevmachine** [comment]
Haha works for end. Thank you ! :D

**Comment by KillerCodeMonkey** [comment]
no probs. Glad that we get this working :)
